import Head from 'next/head';

import Header from '../components/landing/navBar/Header';
import Hero from '../components/landing/hero/Hero';
import Features from '../components/landing/features/Features';
import Pricing from '../components/landing/pricing/Pricing';
import Footer from '../components/landing/footer/Footer';
import Contact from '../components/landing/contact/Contact';

 const LINKS = [
   'Home',
   'Features',
   'Pricing',
   'Sign Up',
   'Log In',
 ]

export default function Home() {
  return (
    <div>
      <Head>
        <title>Get Seafarer - top seamen jobs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Header />
      </nav>
      <main>
        <Hero />
        <Features />
        <Pricing />
        <Contact />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  )
}
